**Numpy** 是 Python 数据分析的基础，很多有关Python数据分析都是建立在其之上。

# 1 ndarray 

整个 numpy 的基础是 ndarray (n dimensional array)，表示同一元素组成的多维数组。
+ dtype 
数据类型
+ shape
由N个正整数组成的元组，每一个元素代表了每一维的大小
+ axes
数组的维数为轴，轴的数量为秩（rank)
Numpy 数组是不变的，一旦创建，就不可与改变

In [1]:
import numpy as np
a = np.array([1,2,3])
print a

[1 2 3]


In [2]:
type(a)

numpy.ndarray

In [3]:
type(a)

numpy.ndarray

In [4]:
a.dtype

dtype('int32')

In [6]:
print a.ndim
print a.size
print a.shape

1
3
(3L,)


创建二维数组

In [8]:
b = np.array([[1.3,2.4],[0.3,4.1]])
print b.dtype
print b.ndim
print b.size
print b.shape

float64
2
4
(2L, 2L)


创建数组既可以通过*list*也可以通过*tuple*,也可以*list*和*tuple*混合使用

In [2]:
import numpy as np
c = np.array([[1,2,3],[4,5,6]])
d = np.array([(7,8,9),(10,11,12)])
e = np.array([[13,14],(12,31),[12,21]])
print c
print d
print e

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[13 14]
 [12 31]
 [12 21]]


Numpy 自带了若干数组创建方法

In [3]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [4]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [5]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,12,3)

array([0, 3, 6, 9])

In [7]:
np.arange(0,6,0.6)

array([ 0. ,  0.6,  1.2,  1.8,  2.4,  3. ,  3.6,  4.2,  4.8,  5.4])

In [8]:
np.arange(0,12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
np.linspace(0,10,5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [10]:
np.linspace(0,10,5,endpoint=True)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [11]:
np.linspace(0,10,5,endpoint=False)

array([ 0.,  2.,  4.,  6.,  8.])

In [12]:
np.random.random(3)

array([ 0.20130582,  0.47024921,  0.51813952])

In [13]:
np.random.random((3,4))

array([[ 0.02214925,  0.63808889,  0.30278891,  0.39861784],
       [ 0.46047649,  0.71827545,  0.99090554,  0.59167459],
       [ 0.60618896,  0.69980344,  0.96309435,  0.02424105]])

# 2 运算操作

## 算术运算

In [1]:
import numpy as np
a = np.arange(4)
print a 
print a+4
print a*2

[0 1 2 3]
[4 5 6 7]
[0 2 4 6]


In [2]:
b = np.arange(4,8)
print b
print a + b
print a - b
print a * b

[4 5 6 7]
[ 4  6  8 10]
[-4 -4 -4 -4]
[ 0  5 12 21]


数学函数运算

In [3]:
print a * np.sin(b)
print a * np.sqrt(b)

[-0.         -0.95892427 -0.558831    1.9709598 ]
[ 0.          2.23606798  4.89897949  7.93725393]


从上面可以看出，对于常见的$+ \space - \space \times $都是每个元素之间的操作

## 矩阵积

矩阵乘法：$$C=A \times B$$

其中$A_{m \times n},B_{n \times p}$，那么矩阵$C_{m \times p}$,其中$$C_{ij}=\sum_{k=0}^{n}A_{ik}*B_{kj}$$

In [4]:
A = np.arange(0,9).reshape(3,3)
B = np.ones((3,3))
print A.dot(B)
print np.dot(A,B)

[[  3.   3.   3.]
 [ 12.  12.  12.]
 [ 21.  21.  21.]]
[[  3.   3.   3.]
 [ 12.  12.  12.]
 [ 21.  21.  21.]]


## 自增操作

In [5]:
a = np.arange(4)
print a
a +=1
print a
a -=2
print a

[0 1 2 3]
[1 2 3 4]
[-1  0  1  2]


## 通用函数

`universal function` 是对数组中的每个元素进行操作

In [6]:
a = np.arange(1,5)
print a
print np.sqrt(a)
print np.log(a)
print np.sin(a)

[1 2 3 4]
[ 1.          1.41421356  1.73205081  2.        ]
[ 0.          0.69314718  1.09861229  1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


## 聚合函数

对数组进行操作，并返回一个数值

In [ ]:
a = np.array([3.3,4.5,5.7,0.3])
